# Generated by Django 5.0.7 on 2024-09-09 16:12

import apps.shop.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regdate', models.DateTimeField(default=apps.shop.models.dtime)),
                ('customer', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('duedate', models.DateField()),
                ('description', models.TextField(default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regdate', models.DateTimeField(default=apps.shop.models.dtime)),
                ('product', models.CharField(max_length=255)),
                ('supplier', models.CharField(max_length=255)),
                ('payment', models.CharField(max_length=10)),
                ('paid', models.BooleanField()),
                ('cost', models.FloatField()),
                ('extra_cost', models.FloatField()),
                ('description', models.TextField(default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
