# Generated by Django 5.0.7 on 2024-09-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='extra_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment',
            field=models.CharField(max_length=3),
        ),
    ]
