# Generated by Django 5.0.7 on 2024-09-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_purchase_extra_cost_alter_purchase_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchasedate',
            field=models.DateField(default=None, null=True),
        ),
    ]
